#!/bin/bash
PROJECT_DIR="/Users/tomwattley/Code/react/racing-api-project/racing-api-frontend"
LOG_FILE="/Users/tomwattley/Code/application_logs/racing-api/racing-api-fe.log"

cd "$PROJECT_DIR" || { echo "Error: Project directory not found."; exit 1; }

npm run dev >> "$LOG_FILE" 2>&1 &

APP_URL="http://localhost:3000/"

sleep 3 

open -a "Google Chrome" "$APP_URL" &
